# Generated by Django 4.0.3 on 2022-03-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lsbDecoding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inputImageName', models.CharField(max_length=100)),
                ('inputImagePath', models.FileField(null=True, upload_to='media/images/', verbose_name='')),
                ('text', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='lsbEncoding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inputImageName', models.CharField(max_length=100)),
                ('inputImagePath', models.FileField(null=True, upload_to='media/images/', verbose_name='')),
                ('text', models.TextField(max_length=250)),
                ('outputImageName', models.CharField(max_length=100)),
                ('outputImagePath', models.FileField(null=True, upload_to='media/images/', verbose_name='')),
            ],
        ),
    ]
