# Generated by Django 4.0.3 on 2022-03-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSBEncode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inputImagePath', models.FileField(upload_to='media/images/', verbose_name='')),
                ('outputImagePath', models.FileField(null=True, upload_to='media/images/', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='lsbEncoding',
        ),
    ]
