# Generated by Django 4.0.3 on 2022-03-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steg', '0002_lsbencode_delete_lsbencoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSBDecode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inputImagePath', models.FileField(null=True, upload_to='media/images/', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='lsbDecoding',
        ),
        migrations.AlterField(
            model_name='lsbencode',
            name='inputImagePath',
            field=models.FileField(upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='lsbencode',
            name='outputImagePath',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
