# Generated by Django 4.0.3 on 2022-03-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steg', '0003_lsbdecode_delete_lsbdecoding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsbdecode',
            name='inputImagePath',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
